var courses = [
    // HTML L1
    {
        title: 'HTML Essential Training',
        url: 'https://www.lynda.com/Web-Development-tutorials/HTML-Essential-Training/170427-2.html',
        description: ' This course provides an in-depth look at the essentials: the syntax of HTML and best practices for writing and editing your code.',
        topic: 'html&css',
        levels: ['L0', 'L1'],
        tags: [],
        skills: ['html'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },
    {
        title: 'HTML5 Structure Syntax Semantics',
        url: 'https://www.lynda.com/HTML-tutorials/HTML5-Structure-Syntax-Semantics/182177-2.html',
        description: 'Gain a deeper understanding of HTML5, and learn how to create richer, more meaningful webpages with HTML5 structural tags and enhanced semantic markup.',
        topic: 'html&css',
        levels: ['L0', 'L1'],
        tags: [],
        skills: ['html'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },
    {
        title: 'HTML Structured Data',
        url: 'https://www.lynda.com/HTML-tutorials/HTML-Structured-Data/363686-2.html',
        description: 'Structured data helps search engines, web crawlers, and browsers extract and process data from a webpage and use it to provide a richer browsing experience for users. Course explains structured data, its benefits, and the various syntaxes you can choose for markup, including microformats, RDFa, microdata, and JSON-LD',
        topic: 'html&css',
        levels: ['L0', 'L1'],
        tags: [],
        skills: ['html'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },
    {
        title: 'Design Web Styling Form Elements',
        url: 'https://www.lynda.com/CSS-tutorials/Design-Web-Styling-Form-Elements/424047-2.html',
        description: '',
        topic: 'html&css',
        levels: ['L1'],
        tags: ['forms'],
        skills: ['html', 'forms'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },
    {
        title: 'HTML & CSS: Creating Forms',
        url: 'https://www.lynda.com/HTML-tutorials/HTML-CSS-Creating-Forms/612196-2.html',
        description: 'Learn how to create forms. Learn proper use of form fields, including the new HTML5 input types, and discover how to add interactivity such as form validation, style forms with CSS, create responsive layouts, add interactivity such as form validation, and design forms for usability and accessibility.',
        topic: 'html&css',
        levels: ['L0', 'L1'],
        tags: ['forms'],
        skills: ['html'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },
    {
        title: 'HTML: Building Tables',
        url: 'https://www.lynda.com/HTML-tutorials/HTML-Building-Tables/365960-2.html',
        description: 'Watch and learn how to build tables with HTML, style tables with CSS, and use best practices to make your table data more meaningful and accessible.',
        topic: 'html&css',
        levels: ['L0', 'L1'],
        tags: ['tables'],
        skills: ['html'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },
    {
        title: 'Learn html',
        url: 'https://www.codecademy.com/learn/learn-html',
        description: 'You will <strong>build two projects</strong> — a fashion blog and a schedule for a wine festival. You will know all the common HTML tags used to structure HTML pages, the skeleton of all websites. You will also be able to create HTML tables to present tabular data efficiently.',
        topic: 'html&css',
        levels: ['L0', 'L1'],
        tags: [],
        skills: ['html'],
        price: ['free'],
        wight: 0,
    },
    {
        title: 'Html fundamentals',
        url: 'https://www.pluralsight.com/courses/html-fundamentals',
        description: 'HTML markup is the heart of any web application and this course will teach you the fundamentals of HTML.',
        topic: 'html&css',
        levels: ['L0', 'L1'],
        tags: [],
        skills: ['html'],
        price: ['free with if you ask CDP'],
        type: ['video', 'course'],
        wight: 0,
    },
    {
        title: 'Html5 fundamentals',
        url: 'https://www.pluralsight.com/courses/html5-fundamentals',
        description: 'In HTML5 Fundamentals, you will learn all about the new and updated markup along with the associated JavaScript APIs that make up the modern web.',
        topic: 'html&css',
        levels: ['L0', 'L1'],
        tags: [],
        skills: ['html'],
        price: ['free with if you ask CDP'],
        type: ['video', 'course'],
        wight: 0,
    },
    {
        title: 'practical-html5',
        url: 'https://www.pluralsight.com/courses/practical-html5',
        description: '',
        topic: 'html&css',
        levels: ['L1'],
        tags: [],
        skills: ['html'],
        price: ['free with if you ask CDP'],
        type: ['video', 'course'],
        wight: 0,
    },
    {
        title: 'Learn html',
        url: 'https://www.w3schools.com/html/default.asp',
        description: 'This course teaches you everything about HTML',
        topic: 'html&css',
        levels: ['L1', 'L2'],
        tags: ['must_for_L1', 'must_for_L2'],
        skills: ['html'],
        price: ['free'],
        type: ['text'],
        wight: 0,
    },

    // HTML L2
    {
        title: 'html5-advanced',
        url: 'https://www.pluralsight.com/courses/practical-html5',
        description: '',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['html'],
        price: ['free with if you ask CDP'],
        type: ['video', 'course'],
        wight: 0,
    },
    {
        title: 'html5-advanced',
        url: 'https://www.pluralsight.com/courses/html5-advanced',
        description: '',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['html'],
        price: ['free with if you ask CDP'],
        type: ['video', 'course'],
        wight: 0,
    },
    {
        title: 'html5-browser-caching',
        url: 'https://www.pluralsight.com/courses/html5-browser-caching',
        description: '',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['html', 'browser-caching'],
        price: ['free with if you ask CDP'],
        type: ['video', 'course'],
        wight: 0,
    },
    {
        title: 'html5-web-storage-indexeddb-file-system',
        url: 'https://www.pluralsight.com/courses/html5-web-storage-indexeddb-file-system',
        description: '',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['html', 'web-storage'],
        price: ['free with if you ask CDP'],
        type: ['video', 'course'],
        wight: 0,
    },
    {
        title: 'html5-audio-video-webrtc',
        url: 'https://www.pluralsight.com/courses/html5-audio-video-webrtc',
        description: '',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['html', 'audio-video'],
        price: ['free with if you ask CDP'],
        type: ['video', 'course'],
        wight: 0,
    },
    {
        title: 'web-components-shadow-dom',
        url: 'https://www.pluralsight.com/courses/web-components-shadow-dom',
        description: '',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['html', 'shadow-dom'],
        price: ['free with if you ask CDP'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'web-accessibility-meeting-guidelines',
        url: 'https://www.pluralsight.com/courses/web-accessibility-meeting-guidelines',
        description: '',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['html', 'web-accessibility'],
        price: ['free with if you ask CDP'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'web-accessibility',
        url: 'https://www.udacity.com/course/web-accessibility--ud891',
        description: '',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['html', 'web-accessibility'],
        price: ['free'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'browser-rendering-optimization',
        url: 'https://www.udacity.com/course/browser-rendering-optimization--ud860',
        description: '',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['html'],
        price: ['free'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'Up-Running-HTML5-Video',
        url: 'https://www.lynda.com/HTML-tutorials/Up-Running-HTML5-Video/135356-2.html',
        description: '',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['html', 'video'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'HTML5-Video-and-Audio-in-Depth',
        url: 'https://www.lynda.com/HTML-5-tutorials/HTML5-Video-and-Audio-in-Depth/80781-2.html',
        description: '',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['html', 'video', 'audio'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'HTML5-Drag-and-Drop-in-Depth',
        url: 'https://www.lynda.com/HTML-5-tutorials/HTML5-Drag-and-Drop-in-Depth/84812-2.html',
        description: '',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['html', 'Drag-and-Drop'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'HTML5-Messaging-Communications-Depth',
        url: 'https://www.lynda.com/HTML-tutorials/HTML5-Messaging-Communications-Depth/92563-2.html',
        description: '',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['html'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'HTML5-Background-Processes-with-Web-Workers',
        url: 'https://www.lynda.com/HTML-5-tutorials/HTML5-Background-Processes-with-Web-Workers/85868-2.html',
        description: '',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['html', 'Web-Workers'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'HTML5-File-API-in-Depth',
        url: 'https://www.lynda.com/HTML-5-tutorials/HTML5-File-API-in-Depth/90369-2.html',
        description: '',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['html'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'HTML5-Document-Editing-in-Depth',
        url: 'https://www.lynda.com/HTML-5-tutorials/HTML5-Document-Editing-in-Depth/85869-2.html',
        description: '',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['html', 'file-api'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },

    // CSS L1

    {
        title: 'Css almanac. Css reference',
        url: 'https://css-tricks.com/almanac/',
        description: 'A reference guide to the many features of CSS. See something that needs to be updated? Let us know!',
        topic: 'html&css',
        levels: ['L1', 'L2'],
        tags: ['must_for_L1', 'must_for_L2'],
        skills: ['css'],
        price: ['free'],
        type: ['text'],
        wight: 0,
    },
    {
        title: 'Learn css',
        url: 'https://www.w3schools.com/css/default.asp',
        description: 'Step by step tutorials will teach you CSS from basic to advanced.',
        topic: 'html&css',
        levels: ['L1', 'L2'],
        tags: ['must_for_L1', 'must_for_L2'],
        skills: ['css'],
        price: ['free'],
        type: ['text'],
        wight: 0,
    },
    {
        title: 'CSS-Fundamentals',
        url: 'https://www.lynda.com/CSS-tutorials/CSS-Fundamentals/417645-2.html',
        description: 'CSS-Fundamentals',
        topic: 'html&css',
        levels: ['L0', 'L1'],
        tags: ['must_for_L1'],
        skills: ['css'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },
    {
        title: 'Making-Sense-CSS-Box-Model',
        url: 'https://www.lynda.com/CSS-tutorials/Making-Sense-CSS-Box-Model/372544-2.html',
        description: 'Making-Sense-CSS-Box-Model',
        topic: 'html&css',
        levels: ['L0', 'L1'],
        tags: ['must_for_L1'],
        skills: ['css'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'CSS-Essential-Training-1',
        url: 'https://www.lynda.com/CSS-tutorials/CSS-Essential-Training-1/569190-2.html',
        description: 'CSS-Essential-Training-1',
        topic: 'html&css',
        levels: ['L0', 'L1'],
        tags: ['must_for_L1'],
        skills: ['css'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'CSS-Essential-Training-2',
        url: 'https://www.lynda.com/CSS-tutorials/CSS-Essential-Training-2/569189-2.html',
        description: 'CSS-Essential-Training-2',
        topic: 'html&css',
        levels: ['L0', 'L1'],
        tags: ['must_for_L1'],
        skills: ['css'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'CSS-Essential-Training-3',
        url: 'https://www.lynda.com/CSS-tutorials/CSS-Essential-Training-3/609030-2.html',
        description: 'CSS-Essential-Training-3',
        topic: 'html&css',
        levels: ['L0', 'L1'],
        tags: ['must_for_L1'],
        skills: ['css'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'CSS-Selectors',
        url: 'https://www.lynda.com/CSS-tutorials/CSS-Selectors/192036-2.html',
        description: 'CSS-Selectors',
        topic: 'html&css',
        levels: ['L0', 'L1'],
        tags: ['must_for_L1'],
        skills: ['css'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'CSS-Frameworks-Grids',
        url: 'https://www.lynda.com/CSS-tutorials/CSS-Frameworks-Grids-2016-Q3-REVISION/504266-2.html',
        description: 'CSS-Frameworks-Grids',
        topic: 'html&css',
        levels: ['L1'],
        tags: ['must_for_L1'],
        skills: ['css'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'codecademy:learn-css',
        url: 'https://www.codecademy.com/learn/learn-css',
        description: 'learn-css',
        topic: 'html&css',
        levels: ['L1'],
        tags: ['must_for_L1'],
        skills: ['css'],
        price: ['free'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'pluralsight: css-intro',
        url: 'https://www.pluralsight.com/courses/css-intro',
        description: 'css-intro',
        topic: 'html&css',
        levels: ['L1'],
        tags: ['must_for_L1'],
        skills: ['css'],
        price: ['Can be free if you ask CPD'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'pluralsight: css-positioning',
        url: 'https://www.pluralsight.com/courses/css-positioning-1834',
        description: 'css-positioning',
        topic: 'html&css',
        levels: ['L1'],
        tags: ['must_for_L1'],
        skills: ['css'],
        price: ['Can be free if you ask CPD'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'pluralsight: better-css',
        url: 'https://www.pluralsight.com/courses/better-css',
        description: 'css-positioning',
        topic: 'html&css',
        levels: ['L2'],
        tags: ['must_for_L1'],
        skills: ['css'],
        price: ['Can be free if you ask CPD'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'pluralsight: responsive-websites-bootstrap3',
        url: 'https://www.pluralsight.com/courses/responsive-websites-bootstrap3',
        description: 'css-positioning',
        topic: 'html&css',
        levels: ['L2'],
        tags: ['must_for_L1'],
        skills: ['css'],
        price: ['Can be free if you ask CPD'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'pluralsight: css3-in-depth',
        url: 'https://www.pluralsight.com/courses/css3-in-depth',
        description: 'css-positioning',
        topic: 'html&css',
        levels: ['L2'],
        tags: ['must_for_L1'],
        skills: ['css'],
        price: ['Can be free if you ask CPD'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'lynda: Advanced-Responsive-Layouts-CSS-Flexbox',
        url: 'https://www.lynda.com/CSS-tutorials/Advanced-Responsive-Layouts-CSS-Flexbox/383780-2.html',
        description: 'css-positioning',
        topic: 'html&css',
        levels: ['L2'],
        tags: ['must_for_L1'],
        skills: ['css', 'flexbox', 'responsive'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'lynda: positioning-best-practices',
        url: 'https://www.lynda.com/CSS-tutorials/positioning-best-practices/47543-2.html',
        description: 'positioning-best-practices',
        topic: 'html&css',
        levels: ['L2'],
        tags: ['must_for_L1'],
        skills: ['css'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'lynda: CSS-Page-Layouts',
        url: 'https://www.lynda.com/Web-Interactive-CSS-training/CSS-Page-Layouts/86003-2.html',
        description: 'CSS-Page-Layouts',
        topic: 'html&css',
        levels: ['L1', 'L2'],
        tags: ['must_for_L1'],
        skills: ['css', 'css-layout', 'css-position'],
        price: ['free with epam'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'codecademy: make-a-website',
        url: 'https://www.codecademy.com/learn/make-a-website',
        description: 'make-a-website',
        topic: 'html&css',
        levels: ['L1', 'L2'],
        tags: ['must_for_L1'],
        skills: ['css', 'css-layout', 'css-position'],
        price: ['free'],
        type: ['video', 'course'],
        wight: 0,
    },

    {
        title: 'css-tricks: centering-in-the-unknown',
        url: 'https://css-tricks.com/centering-in-the-unknown/',
        description: 'css-positioning',
        topic: 'html&css',
        levels: ['L1', 'L2'],
        tags: ['must_for_L1'],
        skills: ['css', 'css-layout', 'css-position'],
        price: ['free'],
        type: ['text'],
        wight: 0,
    },

    {
        title: 'css-tricks: a-guide-to-flexbox',
        url: 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/',
        description: 'a-guide-to-flexbox',
        topic: 'html&css',
        levels: ['L1', 'L2'],
        tags: ['must_for_L1'],
        skills: ['css', 'css-layout', 'css-position', 'flexbox'],
        price: ['free'],
        type: ['text'],
        wight: 0,
    },

    {
        title: 'css-tricks: complete-guide-grid',
        url: 'https://css-tricks.com/snippets/css/complete-guide-grid/',
        description: 'a-guide-to-flexbox',
        topic: 'html&css',
        levels: ['L1', 'L2'],
        tags: ['must_for_L1'],
        skills: ['css', 'css-layout', 'css-position', 'css-grid'],
        price: ['free'],
        type: ['text'],
        wight: 0,
    },

    {
        title: 'css-tricks: complete-guide-grid',
        url: 'https://css-tricks.com/snippets/css/complete-guide-grid/',
        description: 'a-guide-to-flexbox',
        topic: 'html&css',
        levels: ['L1', 'L2'],
        tags: ['must_for_L1'],
        skills: ['css', 'css-layout', 'css-position', 'css-grid'],
        price: ['free'],
        type: ['text'],
        wight: 0,
    },
    {
        title: 'udacity: responsive-images',
        url: 'https://www.udacity.com/course/responsive-images--ud882',
        description: 'a-guide-to-flexbox',
        topic: 'html&css',
        levels: ['L1', 'L2'],
        tags: ['must_for_L1'],
        skills: ['css', 'css-layout', 'responsive'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },
    {
        title: 'udacity: responsive-web-design-fundamentals',
        url: 'https://www.udacity.com/course/responsive-web-design-fundamentals--ud893',
        description: 'responsive-web-design-fundamentals',
        topic: 'html&css',
        levels: ['L1', 'L2'],
        tags: ['must_for_L1'],
        skills: ['css', 'responsive'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },
    {
        title: 'lynda: Creating-Responsive-Web-Design-Advanced-Techniques',
        url: 'https://www.lynda.com/CSS-tutorials/Creating-Responsive-Web-Design-Advanced-Techniques/424045-2.html',
        description: 'responsive-web-design-fundamentals',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['css', 'responsive'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'lynda: CResponsive-Typography-Techniques',
        url: 'https://www.lynda.com/CSS-tutorials/Responsive-Typography-Techniques/133331-2.html',
        description: 'responsive-web-design-fundamentals',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['css', 'responsive'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'lynda: Creating-Responsive-Web-Experience',
        url: 'https://www.lynda.com/CSS-tutorials/Creating-Responsive-Web-Experience/135375-2.html',
        description: 'Creating-Responsive-Web-Experience',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['css', 'responsive'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'lynda: Creating-Responsive-Web-Experience',
        url: 'https://www.lynda.com/CSS-tutorials/Building-Responsive-Single-Page-Design/182174-2.html',
        description: 'Creating-Responsive-Web-Experience',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['css', 'responsive'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'lynda: Making-Your-Site-Retina-Ready',
        url: 'https://www.lynda.com/CSS-tutorials/Making-Your-Site-Retina-Ready/374186-2.html',
        description: 'Creating-Responsive-Web-Experience',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['css', 'responsive'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'codecademy: learn-responsive-design',
        url: 'https://www.codecademy.com/learn/learn-responsive-design',
        description: 'Creating-Responsive-Web-Experience',
        topic: 'html&css',
        levels: ['L2'],
        tags: [],
        skills: ['css', 'responsive'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'youtube:tutsplus: CSS3 Animations',
        url: 'https://www.youtube.com/watch?v=wxZ-U0MwXKU&list=PLaZp2zXwZQ-mQGbj_LQl8wv_CzZ4Xr9l0',
        description: 'youtube:tutsplus: CSS3 Animations',
        topic: 'html&css',
        levels: ['L2', 'L3'],
        tags: [],
        skills: ['css', 'css-animation'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'youtube: tutsplus: html5-canvas',
        url: 'https://www.udacity.com/course/html5-canvas--ud292',
        description: 'youtube:tutsplus: html5-canvas',
        topic: 'html&css',
        levels: ['L2', 'L3'],
        tags: [],
        skills: ['css', 'canvas'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'lynda: Design-Web-CSS-Animated-Rollovers',
        url: 'https://www.lynda.com/CSS-tutorials/Design-Web-CSS-Animated-Rollovers/373561-2.html',
        description: 'youtube:tutsplus: html5-canvas',
        topic: 'html&css',
        levels: ['L2', 'L3'],
        tags: [],
        skills: ['css', 'css-animation'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'lynda: CSS-Gradients',
        url: 'https://www.lynda.com/CSS-tutorials/CSS-Gradients/115467-2.html',
        description: 'CSS-Gradients',
        topic: 'html&css',
        levels: ['L2', 'L3'],
        tags: [],
        skills: ['css', 'css-gradients'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'lynda: CSS-Animation',
        url: 'https://www.lynda.com/CSS-tutorials/CSS-Animation/439683-2.html',
        description: 'CSS-Animation',
        topic: 'html&css',
        levels: ['L2', 'L3'],
        tags: [],
        skills: ['css', 'css-animation'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'youtube:google: Web Accessibility',
        url: 'https://www.youtube.com/watch?v=Ag3DMNbL_ig&list=PLNYkxOF6rcICWx0C9LVWWVqvHlYJyqw7g',
        description: 'CSS-Animation',
        topic: 'html&css',
        levels: ['L2', 'L3'],
        tags: [],
        skills: ['css', 'accessibility'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: '30 Days to Learn HTML & CSS (Full Course)',
        url: 'https://www.youtube.com/watch?v=yTHTo28hwTQ&list=PLgGbWId6zgaWZkPFI4Sc9QXDmmOWa1v5F',
        description: 'CSS-Animation',
        topic: 'html&css',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['html', 'css'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    // TOOLS

    {
        title: 'udacity:version-control-with-git',
        url: 'https://www.udacity.com/course/version-control-with-git--ud123',
        description: 'version-control-with-git',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['git'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },
    //.https://www.udacity.com/course/how-to-use-git-and-github--ud775
    {
        title: 'udacity: how-to-use-git-and-github',
        url: 'https://www.udacity.com/course/how-to-use-git-and-github--ud775',
        description: 'version-control-with-git',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['git'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },
    //
    {
        title: 'lynda:Next-Generation-CSS-Design-PostCSS-CSSNext',
        url: 'https://www.lynda.com/CSS-tutorials/Next-Generation-CSS-Design-PostCSS-CSSNext/483024-2.html',
        description: 'Next-Generation-CSS-Design-PostCSS-CSSNext',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['css', 'post-css', 'css-next'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },
    {
        title: 'lynda:CSS-LESS-SASS',
        url: 'https://www.lynda.com/CSS-tutorials/CSS-LESS-SASS/107921-2.html',
        description: 'CSS-LESS-SASS',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['css', 'less', 'sass'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },
    //
    {
        title: 'lynda:Building-Responsive-Single-Page-Design-PostCSS',
        url: 'https://www.lynda.com/CSS-tutorials/Building-Responsive-Single-Page-Design-PostCSS/417644-2.html',
        description: 'Building-Responsive-Single-Page-Design-PostCSS',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['css', 'post-css'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },
    {
        title: 'Webpack-Deep-Dive',
        url: 'https://www.lynda.com/JavaScript-tutorials/Webpack-Deep-Dive/604264-2.html',
        description: 'Webpack-Deep-Dive',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['css', 'webpack'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'udemy.com: webpack-2-the-complete-developers-guide',
        url: 'https://www.udemy.com/webpack-2-the-complete-developers-guide/',
        description: 'webpack-2-the-complete-developers-guide',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['webpack'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'codecademy: learn-sass',
        url: 'https://www.codecademy.com/learn/learn-sass',
        description: 'learn-sass',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['css', 'sass'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'egghead: js-console-for-power-users',
        url: 'https://egghead.io/courses/js-console-for-power-users',
        description: 'learn-sass',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['console'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    //https://egghead.io/courses/chrome-devtools-sources-panel
    {
        title: 'egghead: chrome-devtools-sources-panel',
        url: 'https://egghead.io/courses/chrome-devtools-sources-panel',
        description: 'learn-sass',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['chrome'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'egghead: learn-the-best-and-most-useful-scss',
        url: 'https://egghead.io/courses/learn-the-best-and-most-useful-scss',
        description: 'learn-the-best-and-most-useful-scss',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['css', 'sass'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'egghead: webpack',
        url: 'https://egghead.io/browse/tools/webpack',
        description: 'webpack',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['css', 'webpack'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'egghead: chrome-devtools',
        url: 'https://egghead.io/browse/tools/chrome-devtools',
        description: 'webpack',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['chrome'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'egghead: git',
        url: 'https://egghead.io/browse/tools/git',
        description: 'git',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['git'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'egghead: npm',
        url: 'https://egghead.io/browse/tools/npm',
        description: 'npm',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['npm'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'egghead: scss',
        url: 'https://egghead.io/browse/tools/scss',
        description: 'scss',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['css', 'sass'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'egghead: gulp',
        url: 'https://egghead.io/browse/tools/gulp',
        description: 'scss',
        topic: 'tools',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['gulp'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    // Javascript

    {
        title: 'learn.javascript.ru',
        url: 'https://learn.javascript.ru',
        description: 'learn.javascript.ru',
        topic: 'javascript',
        levels: ['L1', 'L2', 'L3'],
        tags: [],
        skills: ['js'],
        price: ['free'],
        type: ['text'],
        wight: 0,
    },

    {
        title: 'udacity: javascript-and-the-dom',
        url: 'https://www.udacity.com/course/javascript-and-the-dom--ud117',
        description: 'javascript-and-the-dom',
        topic: 'javascript',
        levels: ['L1'],
        tags: [],
        skills: ['js'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    // https://www.pluralsight.com/courses/quick-start-javascript-2-1917

    {
        title: 'pluralsight: quick-start-javascript-2',
        url: 'https://www.pluralsight.com/courses/quick-start-javascript-2-1917',
        description: 'quick-start-javascript',
        topic: 'javascript',
        levels: ['L1'],
        tags: [],
        skills: ['js'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'pluralsight: quick-start-javascript-3',
        url: 'https://www.pluralsight.com/courses/quick-start-javascript-3-1918',
        description: 'quick-start-javascript',
        topic: 'javascript',
        levels: ['L1'],
        tags: [],
        skills: ['js'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'JavaScript-Essential-Training',
        url: 'https://www.lynda.com/JavaScript-tutorials/JavaScript-Essential-Training/574716-2.html',
        description: 'JavaScript-Essential-Training',
        topic: 'javascript',
        levels: ['L1'],
        tags: [],
        skills: ['js', 'js-basics'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Debugging-Web-JavaScript',
        url: 'https://www.lynda.com/JavaScript-tutorials/Debugging-Web-JavaScript/383908-2.html',
        description: 'Debugging-Web-JavaScript',
        topic: 'javascript',
        levels: ['L1'],
        tags: [],
        skills: ['js', 'js-debugging'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'JavaScript-Functions',
        url: 'https://www.lynda.com/JavaScript-tutorials/JavaScript-Functions/148137-2.html',
        description: 'JavaScript-Functions',
        topic: 'javascript',
        levels: ['L1'],
        tags: [],
        skills: ['js', 'js-function'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },

    //https://www.lynda.com/JavaScript-tutorials/JavaScript-Events/140780-2.html
    {
        title: 'JavaScript-Events',
        url: 'https://www.lynda.com/JavaScript-tutorials/JavaScript-Events/140780-2.html',
        description: 'JavaScript-Events',
        topic: 'javascript',
        levels: ['L1'],
        tags: [],
        skills: ['js', 'js-events'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },
    {
        title: 'JavaScript-Events',
        url: 'https://www.lynda.com/HTML-tutorials/JavaScript-Enhancing-DOM/122462-2.html',
        description: 'JavaScript-Events',
        topic: 'javascript',
        levels: ['L1'],
        tags: [],
        skills: ['js', 'js-working-with-dom'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },
    // https://www.lynda.com/JavaScript-tutorials/JavaScript-JSON/114901-2.html
    {
        title: 'JavaScript-JSON',
        url: 'https://www.lynda.com/JavaScript-tutorials/JavaScript-JSON/114901-2.html',
        description: 'JavaScript-JSON',
        topic: 'javascript',
        levels: ['L1'],
        tags: [],
        skills: ['js', 'json'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },
    {
        title: 'JavaScript-and-AJAX',
        url: 'https://www.lynda.com/Developer-tutorials/JavaScript-and-AJAX/114900-2.html',
        description: 'JavaScript-and-AJAX',
        topic: 'javascript',
        levels: ['L1'],
        tags: [],
        skills: ['js', 'json'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },
    {
        title: 'Organizing-JavaScript-Functionality',
        url: 'https://www.lynda.com/JavaScript-tutorials/Organizing-JavaScript-Functionality/604267-2.html',
        description: 'Organizing-JavaScript-Functionality',
        topic: 'javascript',
        levels: ['L1'],
        tags: [],
        skills: ['js'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },
    //https://www.lynda.com/JavaScript-tutorials/ES6-Right-Parts/604265-2.html
    {
        title: 'lynda: ES6-Right-Parts',
        url: 'https://www.lynda.com/JavaScript-tutorials/ES6-Right-Parts/604265-2.html',
        description: 'ES6-Right-Parts',
        topic: 'javascript',
        levels: ['L1'],
        tags: [],
        skills: ['js'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },
    {
        title: 'codecademy: introduction-to-javascript',
        url: 'https://www.codecademy.com/learn/introduction-to-javascript',
        description: 'introduction-to-javascript',
        topic: 'javascript',
        levels: ['L1'],
        tags: [],
        skills: ['js'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },
    {
        title: 'udemy: understand-javascript',
        url: 'https://www.udemy.com/understand-javascript/',
        description: 'understand-javascript',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['js', 'must_watch'],
        price: ['paid', '10$'],
        type: ['video'],
        wight: 0,
    },
    {
        title: 'udemy: so-you-think-you-know-javascript-1',
        url: 'https://www.udemy.com/so-you-think-you-know-javascript-1/',
        description: 'so-you-think-you-know-javascript-1',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['js', 'must_watch'],
        price: ['paid', '10$'],
        type: ['video'],
        wight: 0,
    },
    {
        title: 'udemy: javascript-es6-tutorial',
        url: 'https://www.udemy.com/javascript-es6-tutorial/',
        description: 'so-you-think-you-know-javascript-1',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['must_watch'],
        skills: ['js', 'es6'],
        price: ['paid', '10$'],
        type: ['video'],
        wight: 0,
    },
    {
        title: 'egghead: chrome-devtools-sources-panel',
        url: 'https://egghead.io/courses/chrome-devtools-sources-panel',
        description: 'chrome-devtools-sources-panel',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['js', 'chrome-devtools'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },
    {
        title: 'egghead: understand-javascript-arrays',
        url: 'https://egghead.io/courses/understand-javascript-arrays',
        description: 'understand-javascript-arrays',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['js', 'javascript-arrays'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },
    {
        title: 'egghead: regex-in-javascript',
        url: 'https://egghead.io/courses/regex-in-javascript',
        description: 'regex-in-javascript',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['js', 'javascript-regex'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'JavaScript Promises',
        url: 'https://www.udacity.com/course/javascript-promises--ud898',
        description: 'Learn how to handle asynchronous work with ease! In this course, you\'ll use Native JavaScript Promises to write asynchronous code that is easy to read, easy to write and easy to debug.',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['promises'],
        skills: ['js', 'javascript-promises'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Object-Oriented JavaScript',
        url: 'https://www.udacity.com/course/object-oriented-javascript--ud711',
        description: 'Object-Oriented JavaScript',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['promises'],
        skills: ['js', 'javascript-oop'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'JavaScript Objects and Prototypes',
        url: 'https://www.pluralsight.com/courses/javascript-objects-prototypes',
        description: 'Object-Oriented JavaScript',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['promises'],
        skills: ['js', 'javascript-oop'],
        price: ['free with CDP'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'JavaScript Design Patterns',
        url: 'https://www.pluralsight.com/courses/javascript-design-patterns',
        description: 'JavaScript Design Patterns',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['promises'],
        skills: ['js', 'javascript-patterns'],
        price: ['free with CDP'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'JavaScript-Templating',
        url: 'https://www.lynda.com/Web-Interaction-Design-tutorials/JavaScript-Templating/156166-2.html',
        description: 'JavaScript Design Patterns',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['js'],
        price: ['free with Epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Learning-Functional-Programming-JavaScript',
        url: 'https://www.lynda.com/JavaScript-tutorials/Learning-Functional-Programming-JavaScript/585272-2.html',
        description: 'Learning-Functional-Programming-JavaScript',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['js'],
        price: ['free with Epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Rethinking-Asynchronous-JavaScript',
        url: 'https://www.lynda.com/JavaScript-tutorials/Rethinking-Asynchronous-JavaScript/604266-2.html',
        description: 'Rethinking-Asynchronous-JavaScript',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['js'],
        price: ['free with Epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'write-simple-asynchronous-code-with-javascript-generators',
        url: 'https://egghead.io/courses/write-simple-asynchronous-code-with-javascript-generators',
        description: 'Rethinking-Asynchronous-JavaScript',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['js'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'es6-javascript-improved',
        url: 'https://www.udacity.com/course/es6-javascript-improved--ud356',
        description: 'Rethinking-Asynchronous-JavaScript',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: [],
        skills: ['js', 'es6'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    // JS L2

    {
        title: 'es6-javascript-improved',
        url: 'https://www.pluralsight.com/courses/javascript-jquery-advanced-techniques',
        description: 'Rethinking-Asynchronous-JavaScript',
        topic: 'javascript',
        levels: ['L2'],
        tags: ['must_watch'],
        skills: ['js'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'javascript-best-practices',
        url: 'https://www.pluralsight.com/courses/javascript-best-practices',
        description: 'javascript-best-practices',
        topic: 'javascript',
        levels: ['L2'],
        tags: ['must_watch'],
        skills: ['js'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'rapid-es6-training',
        url: 'https://www.pluralsight.com/courses/rapid-es6-training',
        description: 'javascript-best-practices',
        topic: 'javascript',
        levels: ['L2'],
        tags: ['must_watch'],
        skills: ['js'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'using-modern-javascript',
        url: 'https://www.udemy.com/using-modern-javascript/',
        description: 'using-modern-javascript',
        topic: 'javascript',
        levels: ['L2', 'L3'],
        tags: ['must_watch'],
        skills: ['js'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'learning-algorithms-in-javascript-from-scratch',
        url: 'https://www.udemy.com/learning-algorithms-in-javascript-from-scratch/',
        description: 'learning-algorithms-in-javascript-from-scratch',
        topic: 'javascript',
        levels: ['L2', 'L3'],
        tags: ['must_watch'],
        skills: ['js'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Modern JavaScript: Building Real-World, Real-Time Apps',
        url: 'https://www.udemy.com/real-world-real-time-modern-javascript/',
        description: 'Modern JavaScript: Building Real-World, Real-Time Apps',
        topic: 'javascript',
        levels: ['L2', 'L3'],
        tags: ['must_watch'],
        skills: ['js'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'mocha',
        url: 'https://egghead.io/browse/libraries/mocha',
        description: 'mocha',
        topic: 'javascript',
        levels: ['L2', 'L3'],
        tags: [],
        skills: ['js'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'jasmine',
        url: 'https://egghead.io/browse/libraries/jasmine',
        description: 'jasmine',
        topic: 'javascript',
        levels: ['L2', 'L3'],
        tags: [],
        skills: ['js'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'chai',
        url: 'https://egghead.io/browse/libraries/chai',
        description: 'chai',
        topic: 'javascript',
        levels: ['L2', 'L3'],
        tags: [],
        skills: ['js'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Reactive JS: Are you ready for the next big paradigm shift?',
        url: 'https://www.udemy.com/reactive-js-getting-ready-for-the-next-big-paradigm-shift/',
        description: 'reactive-js-getting-ready-for-the-next-big-paradigm-shift',
        topic: 'javascript',
        levels: ['L3', 'L4'],
        tags: ['must_watch'],
        skills: ['js'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Learning Data Structures in JavaScript from Scratch',
        url: 'https://www.udemy.com/learning-data-structures-in-javascript-from-scratch/',
        description: 'learning-data-structures-in-javascript-from-scratch',
        topic: 'javascript',
        levels: ['L3', 'L4'],
        tags: ['must_watch'],
        skills: ['js'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'The Coding Interview Bootcamp: Algorithms + Data Structures',
        url: 'https://www.udemy.com/coding-interview-bootcamp-algorithms-and-data-structure/',
        description: 'coding-interview-bootcamp-algorithms-and-data-structure',
        topic: 'javascript',
        levels: ['L3', 'L4'],
        tags: ['must_watch'],
        skills: ['js'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Up-Running-Emberjs',
        url: 'https://www.lynda.com/Emberjs-tutorials/Up-Running-Emberjs/178116-2.html',
        description: 'Up-Running-Emberjs',
        topic: 'javascript',
        levels: ['L1', 'L2', 'L3'],
        tags: ['js_frameworks'],
        skills: ['js', 'Emberjs'],
        price: ['free with Epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'learn-jquery',
        url: 'https://www.codecademy.com/learn/learn-jquery',
        description: 'learn-jquery',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['js_frameworks'],
        skills: ['js', 'jquery'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'intro-to-jquery',
        url: 'https://www.udacity.com/course/intro-to-jquery--ud245',
        description: 'intro-to-jquery',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['js_frameworks'],
        skills: ['js', 'jquery'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Vue-js-Building-Interface',
        url: 'https://www.lynda.com/JavaScript-tutorials/Vue-js-Building-Interface/609025-2.html',
        description: 'Vue-js-Building-Interface',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['js_frameworks'],
        skills: ['js', 'vuejs'],
        price: ['free with Epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Up-Running-Underscorejs',
        url: 'https://www.lynda.com/Underscorejs-tutorials/Up-Running-Underscorejs/145117-2.html',
        description: 'Vue-js-Building-Interface',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['js_frameworks'],
        skills: ['js', 'underscorejs'],
        price: ['free with Epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'jquery',
        url: 'https://egghead.io/browse/libraries/jquery',
        description: 'jquery',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['js_frameworks'],
        skills: ['js', 'jquery'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Vue JS 2 - The Complete Guide (incl. Vue Router & Vuex)',
        url: 'https://www.udemy.com/vuejs-2-the-complete-guide/',
        description: 'Vue JS 2 - The Complete Guide (incl. Vue Router & Vuex)',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['js_frameworks'],
        skills: ['js', 'vuejs'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'learn-to-build-web-apps-using-underscorejs-code-like-a-pro',
        url: 'https://www.udemy.com/learn-to-build-web-apps-using-underscorejs-code-like-a-pro/',
        description: 'learn-to-build-web-apps-using-underscorejs-code-like-a-pro',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['js_frameworks'],
        skills: ['js', 'underscorejs'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Learn meteorjs by building 10 real world projects',
        url: 'https://www.udemy.com/learn-meteorjs-by-building-10-real-world-projects/',
        description: 'Learn meteorjs by building 10 real world projects',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['js_frameworks'],
        skills: ['js', 'meteorjs'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Develop Basic Web Apps with Vue.js',
        url: 'https://egghead.io/courses/develop-basic-web-apps-with-vue-js',
        description: 'Learn meteorjs by building 10 real world projects',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['js_frameworks'],
        skills: ['js', 'vuejs'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Vue.js: 7 courses',
        url: 'https://egghead.io/browse/frameworks/vue',
        description: 'Vue.js: 7 courses',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['js_frameworks'],
        skills: ['js', 'vuejs'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Rxjs: 11 great courses',
        url: 'https://egghead.io/browse/libraries/rxjs',
        description: 'Rxjs: 11 great courses',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['js_frameworks'],
        skills: ['js', 'rxjs'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Lodash',
        url: 'https://egghead.io/browse/libraries/Lodash',
        description: 'Lodash',
        topic: 'javascript',
        levels: ['L1', 'L2'],
        tags: ['js_frameworks'],
        skills: ['js', 'Lodash'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Build a Social Network using Node.js and MongoDB',
        url: 'https://www.udemy.com/build-a-social-network-using-nodejs-and-mongodb/',
        description: 'Build a Social Network using Node.js and MongoDB',
        topic: 'react',
        levels: ['L1', 'L2'],
        tags: ['js_frameworks'],
        skills: ['js', 'nodejs', 'mongodb'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Build an Amazon clone: Nodejs + MongoDB + Stripe Payment',
        url: 'https://www.udemy.com/build-an-amazon-clone-nodejs-stripe-elasticsearch/',
        description: 'Build an Amazon clone: Nodejs + MongoDB + Stripe Payment',
        topic: 'js-fullstack',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'nodejs', 'mongodb'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Learn to Build a Shopping Cart using NodeJS',
        url: 'https://www.udemy.com/learn-to-build-a-shopping-cart-using-nodejs/',
        description: 'Learn to Build a Shopping Cart using NodeJS',
        topic: 'js-fullstack',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'nodejs', 'mongodb'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },


    {
        title: 'The Complete JavaScript Course: Build a Real-World Project',
        url: 'https://www.udemy.com/the-complete-javascript-course/',
        description: 'The Complete JavaScript Course: Build a Real-World Project',
        topic: 'js-fullstack',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'nodejs', 'mongodb'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'web-developer-build-fiverr-twitter-and-mvp-with-nodejs/',
        url: 'https://www.udemy.com/web-developer-build-fiverr-twitter-and-mvp-with-nodejs/',
        description: 'web-developer-build-fiverr-twitter-and-mvp-with-nodejs',
        topic: 'js-fullstack',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'nodejs', 'mongodb'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'React-js-training-tutorials | 23 courses',
        url: 'https://www.lynda.com/React-js-training-tutorials/7049-0.html',
        description: 'React-js-training-tutorials | 23 courses',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'nodejs', 'mongodb'],
        price: ['free with epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'react-101',
        url: 'https://www.codecademy.com/learn/react-101',
        description: 'react-101',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'react-102',
        url: 'https://www.codecademy.com/learn/react-102',
        description: 'react-102',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'React 16 - The Complete Guide (incl. React Router 4 & Redux)',
        url: 'https://www.udemy.com/react-the-complete-guide-incl-redux/',
        description: 'React 16 - The Complete Guide (incl. React Router 4 & Redux)',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'React.js: Building Production Ready Apps, Start to Finish',
        url: 'https://www.udemy.com/reactjs-building-production-ready-apps-start-to-finish/',
        description: 'React.js: Building Production Ready Apps, Start to Finish',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Modern React with Redux',
        url: 'https://www.udemy.com/react-redux/',
        description: 'Modern React with Redux',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks', 'must_watch'],
        skills: ['js', 'reactjs'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'by Dan Abramov: Getting Started with Redux',
        url: 'https://egghead.io/courses/getting-started-with-redux',
        description: 'by Dan Abramov: Getting Started with Redux',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks', 'must_watch'],
        skills: ['js', 'reactjs'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'React Native Fundamentals',
        url: 'https://egghead.io/courses/react-native-fundamentals',
        description: 'React Native Fundamentals',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Start Learning React',
        url: 'https://egghead.io/courses/start-learning-react',
        description: 'React Native Fundamentals',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'react-big-picture',
        url: 'https://www.pluralsight.com/courses/react-big-picture',
        description: 'React Native Fundamentals',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['free with CDP'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'react-js-getting-started',
        url: 'https://www.pluralsight.com/courses/react-js-getting-started',
        description: 'react-js-getting-started',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['free with CDP'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'react-fundamentals',
        url: 'https://www.pluralsight.com/courses/react-fundamentals',
        description: 'react-fundamentals',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['free with CDP'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'REACT 16 FOR EVERYONE',
        url: 'https://www.leveluptutorials.com/store/products/tutorials/lut-dd016',
        description: 'REACT 16 FOR EVERYONE',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['30$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Complete Guide (incl. React Router 4 & Redux)',
        url: 'https://www.udemy.com/react-the-complete-guide-incl-redux/',
        description: 'Complete Guide (incl. React Router 4 & Redux)',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['30$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Add routing to React apps using React Router v4',
        url: 'https://egghead.io/courses/add-routing-to-react-apps-using-react-router-v4',
        description: 'Complete Guide (incl. React Router 4 & Redux)',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'by Dan Abramov: Getting Started with Redux',
        url: 'https://egghead.io/courses/getting-started-with-redux',
        description: 'by Dan Abramov: Getting Started with Redux',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'redux'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'by Dan Abramov: Building React Applications with Idiomatic Redux',
        url: 'https://egghead.io/courses/building-react-applications-with-idiomatic-redux',
        description: 'by Dan Abramov: Building React Applications with Idiomatic Redux',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'redux'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'redux docs',
        url: 'https://redux.js.org/',
        description: 'redux docs',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'redux'],
        price: ['free'],
        type: ['text'],
        wight: 0,
    },

    {
        title: 'React & Redux',
        url: 'https://www.udacity.com/course/react-redux--cx44',
        description: 'React & Redux',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'redux'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'REDUX & REACT FOR EVERYONE',
        url: 'https://www.leveluptutorials.com/store/products/tutorials/lut-dd018',
        description: 'React & Redux',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'redux'],
        price: ['40$'],
        type: ['video'],
        wight: 0,
    },

    //REACT ADVANCED

    {
        title: 'react-flux-building-applications',
        url: 'https://www.pluralsight.com/courses/react-flux-building-applications',
        description: 'react-flux-building-applications',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'redux'],
        price: ['free wirh CDP'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'react-redux-react-router',
        url: 'https://www.pluralsight.com/courses/react-redux-react-router-es6',
        description: 'react-redux-react-router',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'redux'],
        price: ['free wirh CDP'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'react-boilerplate-building-scalable-apps',
        url: 'https://www.pluralsight.com/courses/react-boilerplate-building-scalable-apps',
        description: 'react-boilerplate-building-scalable-apps',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'redux'],
        price: ['free wirh CDP'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'react-styling-components',
        url: 'https://www.pluralsight.com/courses/react-styling-components',
        description: 'react-styling-components',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['free wirh CDP'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'reactjs-advanced',
        url: 'https://www.pluralsight.com/courses/reactjs-advanced',
        description: 'react-styling-components',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['free wirh CDP'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'jest-mastering-react-testing',
        url: 'https://www.pluralsight.com/courses/jest-mastering-react-testing',
        description: 'jest-mastering-react-testing',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['free wirh CDP'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'jest-mastering-react-testing',
        url: 'https://www.pluralsight.com/courses/jest-mastering-react-testing',
        description: 'jest-mastering-react-testing',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['free wirh CDP'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'react-redux-tutorial',
        url: 'https://www.udemy.com/react-redux-tutorial/',
        description: 'react-redux-tutorial',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks', 'must_watch'],
        skills: ['js', 'reactjs', 'redux'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'react-redux-tutorial',
        url: 'https://www.udemy.com/graphql-with-react-course/',
        description: 'react-redux-tutorial',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks', 'must_watch'],
        skills: ['js', 'reactjs', 'redux', 'graphql'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Server Side Rendering with React and Redux',
        url: 'https://www.udemy.com/server-side-rendering-with-react-and-redux/',
        description: 'Server Side Rendering with React and Redux',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks', 'must_watch'],
        skills: ['js', 'reactjs', 'redux', 'ssr'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Leverage New Features of React 16',
        url: 'https://egghead.io/courses/leverage-new-features-of-react-16',
        description: 'Leverage New Features of React 16',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks', 'must_watch'],
        skills: ['js', 'reactjs'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'javascript-redux-simplifying-the-arrow-functions',
        url: 'https://egghead.io/lessons/javascript-redux-simplifying-the-arrow-functions',
        description: 'javascript-redux-simplifying-the-arrow-functions',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'redux'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'async-react-with-redux-saga',
        url: 'https://egghead.io/courses/async-react-with-redux-saga',
        description: 'async-react-with-redux-saga',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'redux'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Full-stack GraphQL with Apollo, Meteor & React',
        url: 'https://www.youtube.com/watch?v=m0TC5DcFHDY&list=PLLnpHn493BHFTDL9M1PKnxQwBwOZ8J-h4',
        description: 'Full-stack GraphQL with Apollo, Meteor & React',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'meteor', 'apollo', 'graphQL'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'GatsbyJS Tutorials',
        url: 'https://www.youtube.com/watch?v=b2H7fWhQcdE&list=PLLnpHn493BHHfoINKLELxDch3uJlSapxg',
        description: 'GatsbyJS Tutorials',
        topic: 'reactjs',
        levels: ['L3', 'L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'GatsbyJS'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'build-a-decentralized-application-for-the-ethereum-blockchain-with-reactjs',
        url: 'https://egghead.io/courses/build-a-decentralized-application-for-the-ethereum-blockchain-with-reactjs',
        description: 'build-a-decentralized-application-for-the-ethereum-blockchain-with-reactjs',
        topic: 'reactjs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'ethereum', 'blockchain'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'up-and-running-with-redux-observable',
        url: 'https://egghead.io/courses/up-and-running-with-redux-observable',
        description: 'up-and-running-with-redux-observable',
        topic: 'reactjs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'redux'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'advanced-react-component-patterns',
        url: 'https://egghead.io/courses/advanced-react-component-patterns',
        description: 'advanced-react-component-patterns',
        topic: 'reactjs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'redux'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'build-a-server-rendered-reactjs-application-with-next-js',
        url: 'https://egghead.io/courses/build-a-server-rendered-reactjs-application-with-next-js',
        description: 'build-a-server-rendered-reactjs-application-with-next-js',
        topic: 'reactjs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'nextjs'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'build-a-server-rendered-code-split-app-in-react-with-react-universal-component',
        url: 'https://egghead.io/courses/build-a-server-rendered-code-split-app-in-react-with-react-universal-component',
        description: 'build-a-server-rendered-code-split-app-in-react-with-react-universal-component',
        topic: 'reactjs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'build-virtual-reality-experiences-using-react-vr',
        url: 'https://egghead.io/courses/build-virtual-reality-experiences-using-react-vr',
        description: 'build-virtual-reality-experiences-using-react-vr',
        topic: 'reactjs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs'],
        price: ['paid'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Learning-Full-Stack-JavaScript-Development-MongoDB-Node-React',
        url: 'https://www.lynda.com/Express-js-tutorials/Learning-Full-Stack-JavaScript-Development-MongoDB-Node-React/533304-2.html',
        description: 'Learning-Full-Stack-JavaScript-Development-MongoDB-Node-React',
        topic: 'reactjs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'fullstack', 'nodejs', 'mongodb'],
        price: ['free with Epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Learning-Full-Stack-JavaScript-Development-MongoDB-Node-React',
        url: 'https://www.lynda.com/Express-js-tutorials/Learning-Full-Stack-JavaScript-Development-MongoDB-Node-React/533304-2.html',
        description: 'Learning-Full-Stack-JavaScript-Development-MongoDB-Node-React',
        topic: 'reactjs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'fullstack', 'nodejs', 'mongodb'],
        price: ['free with Epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'react-express-full-stack-app-build',
        url: 'https://www.pluralsight.com/courses/react-express-full-stack-app-build',
        description: 'react-express-full-stack-app-build',
        topic: 'reactjs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'fullstack', 'nodejs', 'mongodb', 'expressjs'],
        price: ['free with CDP'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'react-express-full-stack-app-build',
        url: 'https://www.pluralsight.com/courses/react-express-full-stack-app-build',
        description: 'react-express-full-stack-app-build',
        topic: 'reactjs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'reactjs', 'fullstack', 'nodejs', 'mongodb', 'express'],
        price: ['free with CDP'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'node-with-react-fullstack-web-development',
        url: 'https://www.udemy.com/node-with-react-fullstack-web-development/',
        description: 'node-with-react-fullstack-web-development',
        topic: 'reactjs',
        levels: ['L4'],
        tags: ['js_frameworks', 'must_watch'],
        skills: ['js', 'reactjs', 'fullstack', 'nodejs', 'mongodb', 'express'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Full stack Universal React with Redux, Node js and MongoDB',
        url: 'https://www.udemy.com/full-stack-universal-react-with-redux-express-and-mongodb/',
        description: 'Full stack Universal React with Redux, Node js and MongoDB',
        topic: 'reactjs',
        levels: ['L4'],
        tags: ['js_frameworks', 'must_watch'],
        skills: ['js', 'reactjs', 'fullstack', 'nodejs', 'mongodb', 'express'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'React JS - Build real world JS apps & deploy on cloud',
        url: 'https://www.udemy.com/reactjs-for-beginners-build-real-world-react-apps-deploy-on-cloud/',
        description: 'Full stack Universal React with Redux, Node js and MongoDB',
        topic: 'reactjs',
        levels: ['L4'],
        tags: ['js_frameworks', 'must_watch'],
        skills: ['js', 'reactjs', 'fullstack', 'nodejs', 'mongodb', 'express'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Build a ProductHunt clone',
        url: 'https://code4startup.com/projects/build-product-hunt-with-reactjs',
        description: 'Build a ProductHunt clone',
        topic: 'reactjs',
        levels: ['L4'],
        tags: ['js_frameworks', 'must_watch'],
        skills: ['js', 'reactjs', 'fullstack', 'nodejs', 'mongodb', 'express'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: '7 courses on react native',
        url: 'https://www.lynda.com/learning-paths/Developer/become-a-react-native-developer',
        description: '7 courses on react native',
        topic: 'react-native',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'react-native'],
        price: ['free with Epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'react-native',
        url: 'https://www.udacity.com/course/react-native--cx45',
        description: 'react-native',
        topic: 'react-native',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'react-native'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'the-complete-react-native-and-redux-course',
        url: 'https://www.udemy.com/the-complete-react-native-and-redux-course/',
        description: 'react-native',
        topic: 'react-native',
        levels: ['L4'],
        tags: ['js_frameworks', 'must_watch'],
        skills: ['js', 'react-native'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'React Native: Advanced Concepts',
        url: 'https://www.udemy.com/react-native-advanced/',
        description: 'React Native: Advanced Concepts',
        topic: 'react-native',
        levels: ['L4'],
        tags: ['js_frameworks', 'must_watch'],
        skills: ['js', 'react-native'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'fundamentals-of-react-native-video',
        url: 'https://egghead.io/courses/fundamentals-of-react-native-video',
        description: 'fundamentals-of-react-native-video',
        topic: 'react-native',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'react-native'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Real World React Native Animations',
        url: 'https://egghead.io/courses/real-world-react-native-animations',
        description: 'fundamentals-of-react-native-video',
        topic: 'react-native',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'react-native'],
        price: ['free'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'REACT NATIVE FOR EVERYONE + LEVEL 2 REACT NATIVE WITH GRAPHQL',
        url: 'https://www.leveluptutorials.com/store/products/tutorials/lut-dd014019',
        description: 'REACT NATIVE FOR EVERYONE + LEVEL 2 REACT NATIVE WITH GRAPHQL',
        topic: 'react-native',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'react-native', 'graphql'],
        price: ['75$'],
        type: ['video'],
        wight: 0,
    },

    // Node Js

    {
        title: '28 courses / 963 Video Tutorials on nodejs',
        url: 'https://www.lynda.com/Node-js-training-tutorials/1283-0.html',
        description: '28 courses / 963 Video Tutorials on nodejs',
        topic: 'nodejs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'nodejs'],
        price: ['free with Epam'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'learning-programming-javascript',
        url: 'https://www.pluralsight.com/courses/learning-programming-javascript',
        description: 'learning-programming-javascript',
        topic: 'nodejs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'nodejs'],
        price: ['free with CDP'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'npm-playbook',
        url: 'https://www.pluralsight.com/courses/npm-playbook',
        description: 'npm-playbook',
        topic: 'nodejs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'nodejs'],
        price: ['free with CDP'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'The Complete Node.js Developer Course (2nd Edition)',
        url: 'https://www.udemy.com/the-complete-nodejs-developer-course-2/',
        description: 'The Complete Node.js Developer Course (2nd Edition)',
        topic: 'nodejs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'nodejs'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'All about NodeJS',
        url: 'https://www.udemy.com/all-about-nodejs/',
        description: 'All about NodeJS',
        topic: 'nodejs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'nodejs'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Learn and Understand NodeJS',
        url: 'https://www.udemy.com/understand-nodejs/',
        description: 'Learn and Understand NodeJS',
        topic: 'nodejs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'nodejs'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

    {
        title: 'Learn and Understand NodeJS',
        url: 'https://www.udemy.com/understand-nodejs/',
        description: 'Learn and Understand NodeJS',
        topic: 'nodejs',
        levels: ['L4'],
        tags: ['js_frameworks'],
        skills: ['js', 'nodejs'],
        price: ['10$'],
        type: ['video'],
        wight: 0,
    },

];