var courses = [
  // HTML L1
  {
    title: 'HTML Essential Training',
    url: 'https://www.lynda.com/Web-Development-tutorials/HTML-Essential-Training/170427-2.html',
    description: ' This course provides an in-depth look at the essentials: the syntax of HTML and best practices for writing and editing your code.',
    topic: 'html&css',
    levels: ['L0', 'L1'],
    tags: [],
    skills: ['html'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  {
    title: 'HTML5 Structure Syntax Semantics',
    url: 'https://www.lynda.com/HTML-tutorials/HTML5-Structure-Syntax-Semantics/182177-2.html',
    description: 'Gain a deeper understanding of HTML5, and learn how to create richer, more meaningful webpages with HTML5 structural tags and enhanced semantic markup.',
    topic: 'html&css',
    levels: ['L0', 'L1'],
    tags: [],
    skills: ['html'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  {
    title: 'HTML Structured Data',
    url: 'https://www.lynda.com/HTML-tutorials/HTML-Structured-Data/363686-2.html',
    description: 'Structured data helps search engines, web crawlers, and browsers extract and process data from a webpage and use it to provide a richer browsing experience for users. Course explains structured data, its benefits, and the various syntaxes you can choose for markup, including microformats, RDFa, microdata, and JSON-LD',
    topic: 'html&css',
    levels: ['L0', 'L1'],
    tags: [],
    skills: ['html'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  {
    title: 'Design Web Styling Form Elements',
    url: 'https://www.lynda.com/CSS-tutorials/Design-Web-Styling-Form-Elements/424047-2.html',
    description: '',
    topic: 'html&css',
    levels: ['L1'],
    tags: ['forms'],
    skills: ['html', 'forms'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  {
    title: 'HTML & CSS: Creating Forms',
    url: 'https://www.lynda.com/HTML-tutorials/HTML-CSS-Creating-Forms/612196-2.html',
    description: 'Learn how to create forms. Learn proper use of form fields, including the new HTML5 input types, and discover how to add interactivity such as form validation, style forms with CSS, create responsive layouts, add interactivity such as form validation, and design forms for usability and accessibility.',
    topic: 'html&css',
    levels: ['L0', 'L1'],
    tags: ['forms'],
    skills: ['html'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  {
    title: 'HTML: Building Tables',
    url: 'https://www.lynda.com/HTML-tutorials/HTML-Building-Tables/365960-2.html',
    description: 'Watch and learn how to build tables with HTML, style tables with CSS, and use best practices to make your table data more meaningful and accessible.',
    topic: 'html&css',
    levels: ['L0', 'L1'],
    tags: ['tables'],
    skills: ['html'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  {
    title: 'Learn html',
    url: 'https://www.codecademy.com/learn/learn-html',
    description: 'You will <strong>build two projects</strong> — a fashion blog and a schedule for a wine festival. You will know all the common HTML tags used to structure HTML pages, the skeleton of all websites. You will also be able to create HTML tables to present tabular data efficiently.',
    topic: 'html&css',
    levels: ['L0', 'L1'],
    tags: [],
    skills: ['html'],
    price: ['free'],
    wight: 0,
  },
  {
    title: 'Html fundamentals',
    url: 'https://www.pluralsight.com/courses/html-fundamentals',
    description: 'HTML markup is the heart of any web application and this course will teach you the fundamentals of HTML.',
    topic: 'html&css',
    levels: ['L0', 'L1'],
    tags: [],
    skills: ['html'],
    price: ['free with if you ask CDP'],
    type: ['video', 'course'],
    wight: 0,
  },
  {
    title: 'Html5 fundamentals',
    url: 'https://www.pluralsight.com/courses/html5-fundamentals',
    description: 'In HTML5 Fundamentals, you will learn all about the new and updated markup along with the associated JavaScript APIs that make up the modern web.',
    topic: 'html&css',
    levels: ['L0', 'L1'],
    tags: [],
    skills: ['html'],
    price: ['free with if you ask CDP'],
    type: ['video', 'course'],
    wight: 0,
  },
  {
    title: 'practical-html5',
    url: 'https://www.pluralsight.com/courses/practical-html5',
    description: '',
    topic: 'html&css',
    levels: ['L1'],
    tags: [],
    skills: ['html'],
    price: ['free with if you ask CDP'],
    type: ['video', 'course'],
    wight: 0,
  },
  {
    title: 'Learn html',
    url: 'https://www.w3schools.com/html/default.asp',
    description: 'This course teaches you everything about HTML',
    topic: 'html&css',
    levels: ['L1', 'L2'],
    tags: ['must_for_L1', 'must_for_L2'],
    skills: ['html'],
    price: ['free'],
    type: ['text'],
    wight: 0,
  },
  
  // HTML L2
  {
    title: 'html5-advanced',
    url: 'https://www.pluralsight.com/courses/practical-html5',
    description: '',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['html'],
    price: ['free with if you ask CDP'],
    type: ['video', 'course'],
    wight: 0,
  },
  {
    title: 'html5-advanced',
    url: 'https://www.pluralsight.com/courses/html5-advanced',
    description: '',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['html'],
    price: ['free with if you ask CDP'],
    type: ['video', 'course'],
    wight: 0,
  },
  {
    title: 'html5-browser-caching',
    url: 'https://www.pluralsight.com/courses/html5-browser-caching',
    description: '',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['html', 'browser-caching'],
    price: ['free with if you ask CDP'],
    type: ['video', 'course'],
    wight: 0,
  },
  {
    title: 'html5-web-storage-indexeddb-file-system',
    url: 'https://www.pluralsight.com/courses/html5-web-storage-indexeddb-file-system',
    description: '',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['html', 'web-storage'],
    price: ['free with if you ask CDP'],
    type: ['video', 'course'],
    wight: 0,
  },
  {
    title: 'html5-audio-video-webrtc',
    url: 'https://www.pluralsight.com/courses/html5-audio-video-webrtc',
    description: '',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['html', 'audio-video'],
    price: ['free with if you ask CDP'],
    type: ['video', 'course'],
    wight: 0,
  },
  {
    title: 'web-components-shadow-dom',
    url: 'https://www.pluralsight.com/courses/web-components-shadow-dom',
    description: '',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['html', 'shadow-dom'],
    price: ['free with if you ask CDP'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'web-accessibility-meeting-guidelines',
    url: 'https://www.pluralsight.com/courses/web-accessibility-meeting-guidelines',
    description: '',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['html', 'web-accessibility'],
    price: ['free with if you ask CDP'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'web-accessibility',
    url: 'https://www.udacity.com/course/web-accessibility--ud891',
    description: '',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['html', 'web-accessibility'],
    price: ['free'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'browser-rendering-optimization',
    url: 'https://www.udacity.com/course/browser-rendering-optimization--ud860',
    description: '',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['html'],
    price: ['free'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'Up-Running-HTML5-Video',
    url: 'https://www.lynda.com/HTML-tutorials/Up-Running-HTML5-Video/135356-2.html',
    description: '',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['html', 'video'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'HTML5-Video-and-Audio-in-Depth',
    url: 'https://www.lynda.com/HTML-5-tutorials/HTML5-Video-and-Audio-in-Depth/80781-2.html',
    description: '',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['html', 'video', 'audio'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'HTML5-Drag-and-Drop-in-Depth',
    url: 'https://www.lynda.com/HTML-5-tutorials/HTML5-Drag-and-Drop-in-Depth/84812-2.html',
    description: '',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['html', 'Drag-and-Drop'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'HTML5-Messaging-Communications-Depth',
    url: 'https://www.lynda.com/HTML-tutorials/HTML5-Messaging-Communications-Depth/92563-2.html',
    description: '',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['html'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'HTML5-Background-Processes-with-Web-Workers',
    url: 'https://www.lynda.com/HTML-5-tutorials/HTML5-Background-Processes-with-Web-Workers/85868-2.html',
    description: '',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['html', 'Web-Workers'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'HTML5-File-API-in-Depth',
    url: 'https://www.lynda.com/HTML-5-tutorials/HTML5-File-API-in-Depth/90369-2.html',
    description: '',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['html'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'HTML5-Document-Editing-in-Depth',
    url: 'https://www.lynda.com/HTML-5-tutorials/HTML5-Document-Editing-in-Depth/85869-2.html',
    description: '',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['html', 'file-api'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  // CSS L1
  
  {
    title: 'Css almanac. Css reference',
    url: 'https://css-tricks.com/almanac/',
    description: 'A reference guide to the many features of CSS. See something that needs to be updated? Let us know!',
    topic: 'html&css',
    levels: ['L1', 'L2'],
    tags: ['must_for_L1', 'must_for_L2'],
    skills: ['css'],
    price: ['free'],
    type: ['text'],
    wight: 0,
  },
  {
    title: 'Learn css',
    url: 'https://www.w3schools.com/css/default.asp',
    description: 'Step by step tutorials will teach you CSS from basic to advanced.',
    topic: 'html&css',
    levels: ['L1', 'L2'],
    tags: ['must_for_L1', 'must_for_L2'],
    skills: ['css'],
    price: ['free'],
    type: ['text'],
    wight: 0,
  },
  {
    title: 'CSS-Fundamentals',
    url: 'https://www.lynda.com/CSS-tutorials/CSS-Fundamentals/417645-2.html',
    description: 'CSS-Fundamentals',
    topic: 'html&css',
    levels: ['L0', 'L1'],
    tags: ['must_for_L1'],
    skills: ['css'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  {
    title: 'Making-Sense-CSS-Box-Model',
    url: 'https://www.lynda.com/CSS-tutorials/Making-Sense-CSS-Box-Model/372544-2.html',
    description: 'Making-Sense-CSS-Box-Model',
    topic: 'html&css',
    levels: ['L0', 'L1'],
    tags: ['must_for_L1'],
    skills: ['css'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'CSS-Essential-Training-1',
    url: 'https://www.lynda.com/CSS-tutorials/CSS-Essential-Training-1/569190-2.html',
    description: 'CSS-Essential-Training-1',
    topic: 'html&css',
    levels: ['L0', 'L1'],
    tags: ['must_for_L1'],
    skills: ['css'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'CSS-Essential-Training-2',
    url: 'https://www.lynda.com/CSS-tutorials/CSS-Essential-Training-2/569189-2.html',
    description: 'CSS-Essential-Training-2',
    topic: 'html&css',
    levels: ['L0', 'L1'],
    tags: ['must_for_L1'],
    skills: ['css'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'CSS-Essential-Training-3',
    url: 'https://www.lynda.com/CSS-tutorials/CSS-Essential-Training-3/609030-2.html',
    description: 'CSS-Essential-Training-3',
    topic: 'html&css',
    levels: ['L0', 'L1'],
    tags: ['must_for_L1'],
    skills: ['css'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'CSS-Selectors',
    url: 'https://www.lynda.com/CSS-tutorials/CSS-Selectors/192036-2.html',
    description: 'CSS-Selectors',
    topic: 'html&css',
    levels: ['L0', 'L1'],
    tags: ['must_for_L1'],
    skills: ['css'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'CSS-Frameworks-Grids',
    url: 'https://www.lynda.com/CSS-tutorials/CSS-Frameworks-Grids-2016-Q3-REVISION/504266-2.html',
    description: 'CSS-Frameworks-Grids',
    topic: 'html&css',
    levels: ['L1'],
    tags: ['must_for_L1'],
    skills: ['css'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'codecademy:learn-css',
    url: 'https://www.codecademy.com/learn/learn-css',
    description: 'learn-css',
    topic: 'html&css',
    levels: ['L1'],
    tags: ['must_for_L1'],
    skills: ['css'],
    price: ['free'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'pluralsight: css-intro',
    url: 'https://www.pluralsight.com/courses/css-intro',
    description: 'css-intro',
    topic: 'html&css',
    levels: ['L1'],
    tags: ['must_for_L1'],
    skills: ['css'],
    price: ['Can be free if you ask CPD'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'pluralsight: css-positioning',
    url: 'https://www.pluralsight.com/courses/css-positioning-1834',
    description: 'css-positioning',
    topic: 'html&css',
    levels: ['L1'],
    tags: ['must_for_L1'],
    skills: ['css'],
    price: ['Can be free if you ask CPD'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'pluralsight: better-css',
    url: 'https://www.pluralsight.com/courses/better-css',
    description: 'css-positioning',
    topic: 'html&css',
    levels: ['L2'],
    tags: ['must_for_L1'],
    skills: ['css'],
    price: ['Can be free if you ask CPD'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'pluralsight: responsive-websites-bootstrap3',
    url: 'https://www.pluralsight.com/courses/responsive-websites-bootstrap3',
    description: 'css-positioning',
    topic: 'html&css',
    levels: ['L2'],
    tags: ['must_for_L1'],
    skills: ['css'],
    price: ['Can be free if you ask CPD'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'pluralsight: css3-in-depth',
    url: 'https://www.pluralsight.com/courses/css3-in-depth',
    description: 'css-positioning',
    topic: 'html&css',
    levels: ['L2'],
    tags: ['must_for_L1'],
    skills: ['css'],
    price: ['Can be free if you ask CPD'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'lynda: Advanced-Responsive-Layouts-CSS-Flexbox',
    url: 'https://www.lynda.com/CSS-tutorials/Advanced-Responsive-Layouts-CSS-Flexbox/383780-2.html',
    description: 'css-positioning',
    topic: 'html&css',
    levels: ['L2'],
    tags: ['must_for_L1'],
    skills: ['css', 'flexbox', 'responsive'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'lynda: positioning-best-practices',
    url: 'https://www.lynda.com/CSS-tutorials/positioning-best-practices/47543-2.html',
    description: 'positioning-best-practices',
    topic: 'html&css',
    levels: ['L2'],
    tags: ['must_for_L1'],
    skills: ['css'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'lynda: CSS-Page-Layouts',
    url: 'https://www.lynda.com/Web-Interactive-CSS-training/CSS-Page-Layouts/86003-2.html',
    description: 'CSS-Page-Layouts',
    topic: 'html&css',
    levels: ['L1', 'L2'],
    tags: ['must_for_L1'],
    skills: ['css', 'css-layout', 'css-position'],
    price: ['free with epam'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'codecademy: make-a-website',
    url: 'https://www.codecademy.com/learn/make-a-website',
    description: 'make-a-website',
    topic: 'html&css',
    levels: ['L1', 'L2'],
    tags: ['must_for_L1'],
    skills: ['css', 'css-layout', 'css-position'],
    price: ['free'],
    type: ['video', 'course'],
    wight: 0,
  },
  
  {
    title: 'css-tricks: centering-in-the-unknown',
    url: 'https://css-tricks.com/centering-in-the-unknown/',
    description: 'css-positioning',
    topic: 'html&css',
    levels: ['L1', 'L2'],
    tags: ['must_for_L1'],
    skills: ['css', 'css-layout', 'css-position'],
    price: ['free'],
    type: ['text'],
    wight: 0,
  },
  
  {
    title: 'css-tricks: a-guide-to-flexbox',
    url: 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/',
    description: 'a-guide-to-flexbox',
    topic: 'html&css',
    levels: ['L1', 'L2'],
    tags: ['must_for_L1'],
    skills: ['css', 'css-layout', 'css-position', 'flexbox'],
    price: ['free'],
    type: ['text'],
    wight: 0,
  },
  
  {
    title: 'css-tricks: complete-guide-grid',
    url: 'https://css-tricks.com/snippets/css/complete-guide-grid/',
    description: 'a-guide-to-flexbox',
    topic: 'html&css',
    levels: ['L1', 'L2'],
    tags: ['must_for_L1'],
    skills: ['css', 'css-layout', 'css-position', 'css-grid'],
    price: ['free'],
    type: ['text'],
    wight: 0,
  },
  
  {
    title: 'css-tricks: complete-guide-grid',
    url: 'https://css-tricks.com/snippets/css/complete-guide-grid/',
    description: 'a-guide-to-flexbox',
    topic: 'html&css',
    levels: ['L1', 'L2'],
    tags: ['must_for_L1'],
    skills: ['css', 'css-layout', 'css-position', 'css-grid'],
    price: ['free'],
    type: ['text'],
    wight: 0,
  },
  {
    title: 'udacity: responsive-images',
    url: 'https://www.udacity.com/course/responsive-images--ud882',
    description: 'a-guide-to-flexbox',
    topic: 'html&css',
    levels: ['L1', 'L2'],
    tags: ['must_for_L1'],
    skills: ['css', 'css-layout', 'responsive'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  {
    title: 'udacity: responsive-web-design-fundamentals',
    url: 'https://www.udacity.com/course/responsive-web-design-fundamentals--ud893',
    description: 'responsive-web-design-fundamentals',
    topic: 'html&css',
    levels: ['L1', 'L2'],
    tags: ['must_for_L1'],
    skills: ['css', 'responsive'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  {
    title: 'lynda: Creating-Responsive-Web-Design-Advanced-Techniques',
    url: 'https://www.lynda.com/CSS-tutorials/Creating-Responsive-Web-Design-Advanced-Techniques/424045-2.html',
    description: 'responsive-web-design-fundamentals',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['css', 'responsive'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'lynda: CResponsive-Typography-Techniques',
    url: 'https://www.lynda.com/CSS-tutorials/Responsive-Typography-Techniques/133331-2.html',
    description: 'responsive-web-design-fundamentals',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['css', 'responsive'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'lynda: Creating-Responsive-Web-Experience',
    url: 'https://www.lynda.com/CSS-tutorials/Creating-Responsive-Web-Experience/135375-2.html',
    description: 'Creating-Responsive-Web-Experience',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['css', 'responsive'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'lynda: Creating-Responsive-Web-Experience',
    url: 'https://www.lynda.com/CSS-tutorials/Building-Responsive-Single-Page-Design/182174-2.html',
    description: 'Creating-Responsive-Web-Experience',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['css', 'responsive'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'lynda: Making-Your-Site-Retina-Ready',
    url: 'https://www.lynda.com/CSS-tutorials/Making-Your-Site-Retina-Ready/374186-2.html',
    description: 'Creating-Responsive-Web-Experience',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['css', 'responsive'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'codecademy: learn-responsive-design',
    url: 'https://www.codecademy.com/learn/learn-responsive-design',
    description: 'Creating-Responsive-Web-Experience',
    topic: 'html&css',
    levels: ['L2'],
    tags: [],
    skills: ['css', 'responsive'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'youtube:tutsplus: CSS3 Animations',
    url: 'https://www.youtube.com/watch?v=wxZ-U0MwXKU&list=PLaZp2zXwZQ-mQGbj_LQl8wv_CzZ4Xr9l0',
    description: 'youtube:tutsplus: CSS3 Animations',
    topic: 'html&css',
    levels: ['L2', 'L3'],
    tags: [],
    skills: ['css', 'css-animation'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'youtube: tutsplus: html5-canvas',
    url: 'https://www.udacity.com/course/html5-canvas--ud292',
    description: 'youtube:tutsplus: html5-canvas',
    topic: 'html&css',
    levels: ['L2', 'L3'],
    tags: [],
    skills: ['css', 'canvas'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'lynda: Design-Web-CSS-Animated-Rollovers',
    url: 'https://www.lynda.com/CSS-tutorials/Design-Web-CSS-Animated-Rollovers/373561-2.html',
    description: 'youtube:tutsplus: html5-canvas',
    topic: 'html&css',
    levels: ['L2', 'L3'],
    tags: [],
    skills: ['css', 'css-animation'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'lynda: CSS-Gradients',
    url: 'https://www.lynda.com/CSS-tutorials/CSS-Gradients/115467-2.html',
    description: 'CSS-Gradients',
    topic: 'html&css',
    levels: ['L2', 'L3'],
    tags: [],
    skills: ['css', 'css-gradients'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'lynda: CSS-Animation',
    url: 'https://www.lynda.com/CSS-tutorials/CSS-Animation/439683-2.html',
    description: 'CSS-Animation',
    topic: 'html&css',
    levels: ['L2', 'L3'],
    tags: [],
    skills: ['css', 'css-animation'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'youtube:google: Web Accessibility',
    url: 'https://www.youtube.com/watch?v=Ag3DMNbL_ig&list=PLNYkxOF6rcICWx0C9LVWWVqvHlYJyqw7g',
    description: 'CSS-Animation',
    topic: 'html&css',
    levels: ['L2', 'L3'],
    tags: [],
    skills: ['css', 'accessibility'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: '30 Days to Learn HTML & CSS (Full Course)',
    url: 'https://www.youtube.com/watch?v=yTHTo28hwTQ&list=PLgGbWId6zgaWZkPFI4Sc9QXDmmOWa1v5F',
    description: 'CSS-Animation',
    topic: 'html&css',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['html', 'css'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  
  // TOOLS
  
  {
    title: 'udacity:version-control-with-git',
    url: 'https://www.udacity.com/course/version-control-with-git--ud123',
    description: 'version-control-with-git',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['git'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  //.https://www.udacity.com/course/how-to-use-git-and-github--ud775
  {
    title: 'udacity: how-to-use-git-and-github',
    url: 'https://www.udacity.com/course/how-to-use-git-and-github--ud775',
    description: 'version-control-with-git',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['git'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  //
  {
    title: 'lynda:Next-Generation-CSS-Design-PostCSS-CSSNext',
    url: 'https://www.lynda.com/CSS-tutorials/Next-Generation-CSS-Design-PostCSS-CSSNext/483024-2.html',
    description: 'Next-Generation-CSS-Design-PostCSS-CSSNext',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['css', 'post-css', 'css-next'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  {
    title: 'lynda:CSS-LESS-SASS',
    url: 'https://www.lynda.com/CSS-tutorials/CSS-LESS-SASS/107921-2.html',
    description: 'CSS-LESS-SASS',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['css', 'less', 'sass'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  //
  {
    title: 'lynda:Building-Responsive-Single-Page-Design-PostCSS',
    url: 'https://www.lynda.com/CSS-tutorials/Building-Responsive-Single-Page-Design-PostCSS/417644-2.html',
    description: 'Building-Responsive-Single-Page-Design-PostCSS',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['css', 'post-css'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  {
    title: 'Webpack-Deep-Dive',
    url: 'https://www.lynda.com/JavaScript-tutorials/Webpack-Deep-Dive/604264-2.html',
    description: 'Webpack-Deep-Dive',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['css', 'webpack'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'udemy.com: webpack-2-the-complete-developers-guide',
    url: 'https://www.udemy.com/webpack-2-the-complete-developers-guide/',
    description: 'webpack-2-the-complete-developers-guide',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['webpack'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'codecademy: learn-sass',
    url: 'https://www.codecademy.com/learn/learn-sass',
    description: 'learn-sass',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['css', 'sass'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'egghead: js-console-for-power-users',
    url: 'https://egghead.io/courses/js-console-for-power-users',
    description: 'learn-sass',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['console'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  
  //https://egghead.io/courses/chrome-devtools-sources-panel
  {
    title: 'egghead: chrome-devtools-sources-panel',
    url: 'https://egghead.io/courses/chrome-devtools-sources-panel',
    description: 'learn-sass',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['chrome'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'egghead: learn-the-best-and-most-useful-scss',
    url: 'https://egghead.io/courses/learn-the-best-and-most-useful-scss',
    description: 'learn-the-best-and-most-useful-scss',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['css', 'sass'],
    price: ['paid'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'egghead: webpack',
    url: 'https://egghead.io/browse/tools/webpack',
    description: 'webpack',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['css', 'webpack'],
    price: ['paid'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'egghead: chrome-devtools',
    url: 'https://egghead.io/browse/tools/chrome-devtools',
    description: 'webpack',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['chrome'],
    price: ['paid'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'egghead: git',
    url: 'https://egghead.io/browse/tools/git',
    description: 'git',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['git'],
    price: ['paid'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'egghead: npm',
    url: 'https://egghead.io/browse/tools/npm',
    description: 'npm',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['npm'],
    price: ['paid'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'egghead: scss',
    url: 'https://egghead.io/browse/tools/scss',
    description: 'scss',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['css', 'sass'],
    price: ['paid'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'egghead: gulp',
    url: 'https://egghead.io/browse/tools/gulp',
    description: 'scss',
    topic: 'tools',
    levels: ['L1', 'L2'],
    tags: [],
    skills: ['gulp'],
    price: ['paid'],
    type: ['video'],
    wight: 0,
  },
  
  // Javascript
  
  {
    title: 'learn.javascript.ru',
    url: 'https://learn.javascript.ru',
    description: 'learn.javascript.ru',
    topic: 'javascript',
    levels: ['L1', 'L2', 'L3'],
    tags: [],
    skills: ['js'],
    price: ['free'],
    type: ['text'],
    wight: 0,
  },
  
  {
    title: 'udacity: javascript-and-the-dom',
    url: 'https://www.udacity.com/course/javascript-and-the-dom--ud117',
    description: 'javascript-and-the-dom',
    topic: 'javascript',
    levels: ['L1'],
    tags: [],
    skills: ['js'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  
  // https://www.pluralsight.com/courses/quick-start-javascript-2-1917
  
  {
    title: 'pluralsight: quick-start-javascript-2',
    url: 'https://www.pluralsight.com/courses/quick-start-javascript-2-1917',
    description: 'quick-start-javascript',
    topic: 'javascript',
    levels: ['L1'],
    tags: [],
    skills: ['js'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'pluralsight: quick-start-javascript-3',
    url: 'https://www.pluralsight.com/courses/quick-start-javascript-3-1918',
    description: 'quick-start-javascript',
    topic: 'javascript',
    levels: ['L1'],
    tags: [],
    skills: ['js'],
    price: ['free'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'JavaScript-Essential-Training',
    url: 'https://www.lynda.com/JavaScript-tutorials/JavaScript-Essential-Training/574716-2.html',
    description: 'JavaScript-Essential-Training',
    topic: 'javascript',
    levels: ['L1'],
    tags: [],
    skills: ['js', 'js-basics'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'Debugging-Web-JavaScript',
    url: 'https://www.lynda.com/JavaScript-tutorials/Debugging-Web-JavaScript/383908-2.html',
    description: 'Debugging-Web-JavaScript',
    topic: 'javascript',
    levels: ['L1'],
    tags: [],
    skills: ['js', 'js-debugging'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
  
  {
    title: 'JavaScript-Functions',
    url: 'https://www.lynda.com/JavaScript-tutorials/JavaScript-Functions/148137-2.html',
    description: 'JavaScript-Functions',
    topic: 'javascript',
    levels: ['L1'],
    tags: [],
    skills: ['js', 'js-function'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
    
    //https://www.lynda.com/JavaScript-tutorials/JavaScript-Events/140780-2.html
  {
    title: 'JavaScript-Events',
    url: 'https://www.lynda.com/JavaScript-tutorials/JavaScript-Events/140780-2.html',
    description: 'JavaScript-Events',
    topic: 'javascript',
    levels: ['L1'],
    tags: [],
    skills: ['js', 'js-events'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
  {
    title: 'JavaScript-Events',
    url: 'https://www.lynda.com/HTML-tutorials/JavaScript-Enhancing-DOM/122462-2.html',
    description: 'JavaScript-Events',
    topic: 'javascript',
    levels: ['L1'],
    tags: [],
    skills: ['js', 'js-working-with-dom'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
  // https://www.lynda.com/JavaScript-tutorials/JavaScript-JSON/114901-2.html
  {
    title: 'JavaScript-JSON',
    url: 'https://www.lynda.com/JavaScript-tutorials/JavaScript-JSON/114901-2.html',
    description: 'JavaScript-JSON',
    topic: 'javascript',
    levels: ['L1'],
    tags: [],
    skills: ['js', 'json'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
  {
    title: 'JavaScript-and-AJAX',
    url: 'https://www.lynda.com/Developer-tutorials/JavaScript-and-AJAX/114900-2.html',
    description: 'JavaScript-and-AJAX',
    topic: 'javascript',
    levels: ['L1'],
    tags: [],
    skills: ['js', 'json'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
  {
    title: 'Organizing-JavaScript-Functionality',
    url: 'https://www.lynda.com/JavaScript-tutorials/Organizing-JavaScript-Functionality/604267-2.html',
    description: 'Organizing-JavaScript-Functionality',
    topic: 'javascript',
    levels: ['L1'],
    tags: [],
    skills: ['js'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
    //https://www.lynda.com/JavaScript-tutorials/ES6-Right-Parts/604265-2.html
  {
    title: 'lynda: ES6-Right-Parts',
    url: 'https://www.lynda.com/JavaScript-tutorials/ES6-Right-Parts/604265-2.html',
    description: 'ES6-Right-Parts',
    topic: 'javascript',
    levels: ['L1'],
    tags: [],
    skills: ['js'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
  {
    title: 'codecademy: introduction-to-javascript',
    url: 'https://www.codecademy.com/learn/introduction-to-javascript',
    description: 'introduction-to-javascript',
    topic: 'javascript',
    levels: ['L1'],
    tags: [],
    skills: ['js'],
    price: ['free with epam'],
    type: ['video'],
    wight: 0,
  },
  {
    title: 'udemy: understand-javascript',
    url: 'https://www.udemy.com/understand-javascript/',
    description: 'understand-javascript',
    topic: 'javascript',
    levels: ['L1','L2'],
    tags: [],
    skills: ['js', 'must_watch'],
    price: ['paid','10$'],
    type: ['video'],
    wight: 0,
  },
  {
    title: 'udemy: so-you-think-you-know-javascript-1',
    url: 'https://www.udemy.com/so-you-think-you-know-javascript-1/',
    description: 'so-you-think-you-know-javascript-1',
    topic: 'javascript',
    levels: ['L1','L2'],
    tags: [],
    skills: ['js', 'must_watch'],
    price: ['paid','10$'],
    type: ['video'],
    wight: 0,
  },
  {
    title: 'udemy: javascript-es6-tutorial',
    url: 'https://www.udemy.com/javascript-es6-tutorial/',
    description: 'so-you-think-you-know-javascript-1',
    topic: 'javascript',
    levels: ['L1','L2'],
    tags: ['must_watch'],
    skills: ['js', 'es6'],
    price: ['paid','10$'],
    type: ['video'],
    wight: 0,
  },
  {
    title: 'egghead: chrome-devtools-sources-panel',
    url: 'https://egghead.io/courses/chrome-devtools-sources-panel',
    description: 'chrome-devtools-sources-panel',
    topic: 'javascript',
    levels: ['L1','L2'],
    tags: [],
    skills: ['js', 'chrome-devtools'],
    price: ['paid'],
    type: ['video'],
    wight: 0,
  },
  {
    title: 'egghead: understand-javascript-arrays',
    url: 'https://egghead.io/courses/understand-javascript-arrays',
    description: 'understand-javascript-arrays',
    topic: 'javascript',
    levels: ['L1','L2'],
    tags: [],
    skills: ['js', 'javascript-arrays'],
    price: ['paid'],
    type: ['video'],
    wight: 0,
  },
  {
    title: 'egghead: regex-in-javascript',
    url: 'https://egghead.io/courses/regex-in-javascript',
    description: 'regex-in-javascript',
    topic: 'javascript',
    levels: ['L1','L2'],
    tags: [],
    skills: ['js', 'javascript-regex'],
    price: ['paid'],
    type: ['video'],
    wight: 0,
  },
];